apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: microservices
  source:
    repoURL: https://github.com/mahesh-newdevops/microservices-apps-deploy.git
    targetRevision: main
    path: charts/microservice
    helm:
      valueFiles:
        - ../../environments/dev/order-service-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
