nameOverride: frontend
fullnameOverride: frontend
replicaCount: 1

image:
  repository: ghcr.io/mahesh-newdevops/frontend
  tag: 6dfb126b6798c890de2cbdd83105dbc794d5271a

env:
  SERVICE_NAME: frontend
  PORT: "80"

service:
  port: 80
  targetPort: 80

health:
  path: /

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/group.name: microservices-dev
    alb.ingress.kubernetes.io/group.order: "100"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: ""
  path: /
  pathType: Prefix
