nameOverride: notification-service
fullnameOverride: notification-service
replicaCount: 1

image:
  repository: ghcr.io/mahesh-newdevops/notification-service
  tag: latest

env:
  SERVICE_NAME: notification-service
  PORT: "3000"

service:
  port: 80
  targetPort: 3000

health:
  path: /health

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/group.name: microservices-dev
    alb.ingress.kubernetes.io/group.order: "40"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: ""
  path: /api/notifications
  pathType: Prefix
