nameOverride: order-service
fullnameOverride: order-service
replicaCount: 1

image:
  repository: ghcr.io/mahesh-newdevops/order-service
  tag: latest

env:
  SERVICE_NAME: order-service
  PORT: "3000"

service:
  port: 80
  targetPort: 3000
