nameOverride: order-service
fullnameOverride: order-service
replicaCount: 1

image:
  repository: ghcr.io/mahesh-newdevops/order-service
  tag: 6dfb126b6798c890de2cbdd83105dbc794d5271a

env:
  SERVICE_NAME: order-service
  PORT: "3000"
  USER_SERVICE_URL: http://user-service

service:
  port: 80
  targetPort: 3000

health:
  path: /health

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/group.name: microservices-dev
    alb.ingress.kubernetes.io/group.order: "20"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: ""
  path: /api/orders
  pathType: Prefix
