nameOverride: user-service
fullnameOverride: user-service
replicaCount: 1

image:
  repository: ghcr.io/mahesh-newdevops/user-service
  tag: latest

env:
  SERVICE_NAME: user-service
  PORT: "3000"

service:
  port: 80
  targetPort: 3000
